# Generated by Django 3.1.1 on 2021-07-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20210714_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
