# Generated by Django 3.1.1 on 2021-07-14 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_banner_show'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='link',
            new_name='url',
        ),
    ]
